import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getPages } from "@/sanity/sanity.utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en" className="max-w-5xl mx-auto py-5">
      <body className={inter.className}>
        <div>
          {pages.map((page) => (
            <Link key={page._id} href={`/${page.slug}`}>
              {page.title}
            </Link>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
